### ISSUE TITLE
Refinery "waste" not merged to following chains

### ISSUE THREAD

**Issue by fzilic** [AnthorNet/SC-ProductionPlanner#15]
When attempting to plan production of plastic and rubber from single Oil Extractor adding residual fuel does not take aggregated input of residuals.

For example.
Take a oil extractor on normal node (producing 120 m3 of crude oil), and then add production for 40 units of plastic and 40 units of rubber.

It will take 4 refineries to produce that many, plus it produces 60 m3 of heavy oil residue (combined from all refineries). 

![image](https://user-images.githubusercontent.com/1804667/111981120-8659dc00-8b07-11eb-8cc4-38d070c9b138.png)

We could reuse that heavy oil residue by producing residual fuel in a single refinery taking in 60 m3 of heavy oil residue and producing 40 m3 of fuel. If we add fuel production from previous plan to produce 40 m3 of fuel from oil residue, we get something like this.

![Actual](https://user-images.githubusercontent.com/1804667/111981044-6cb89480-8b07-11eb-8a46-41e4b42d31c6.jpg)

In game I have tested out, and I have a line that would look something like this:

![reality](https://user-images.githubusercontent.com/1804667/111981352-dafd5700-8b07-11eb-828d-a46b0c81d3ca.jpg)

**Comment by lognz** [comment]
![another example](https://user-images.githubusercontent.com/40216422/206908619-1378f768-241c-4eaa-9e19-6368ac8580b4.png)

Another Example of Heavy Oil Residue not being utilized.

https://satisfactory-calculator.com/en/planners/production/index/json/%7B%22Desc_LiquidTurboFuel_C%22%3A%22307%22%2C%22Desc_Filter_C%22%3A%227.5%22%2C%22input%22%3A%7B%22Desc_CompactedCoal_C%22%3A%22340%22%7D%2C%22altRecipes%22%3A%5B%22Recipe_Alternate_TurboHeavyFuel_C%22%2C%22Recipe_Alternate_HeavyOilResidue_C%22%2C%22Recipe_Alternate_PolyesterFabric_C%22%5D%7D

It would have saved me from a bunch of extra calculations if instead of the 15 heavy oil residue being waste, the calculator saw that I am also making Heavy Oil Residue in another step and routed it in. 

Without doing that, it appears I need 311 oil to make this production work, but you really only need 302. 

I believe the calculator already does this successfully with aluminum builds where it routes the output water back into inputs.
