### ISSUE TITLE
[Feature Request] Option for a grid view with building snapping for the production planner network graph

### ISSUE THREAD

**Issue by Slayerfroggie** [AnthorNet/SC-ProductionPlanner#34]
Just something that would make it easier to rearrange your network graph in addition to the current freeform method by being able to snap the buildings to some grid lines, as well as being able to switch between these graph modes. I like the current free form method, but would prefer something on top of it to make it a bit more rigid for planning/rearranging to reflect how it potentially will layout in the game. I'm happy to work with the current graph system, just thought it might be a nice extra feature.

**Comment by Atreidae** [comment]
Id love this. But I'm sure it would be a pita to code.

Personally I'd line the ability to say "I have X resources how many y can I make in the most efficient way possible"

Rather than today saying I want to make 10 of something and deselecting all the alts that require ingredients I don't have.. then tweaking the output number
