### ISSUE TITLE
New fuel genrator fuels are broken in the power planner.

### ISSUE THREAD

**Issue by Ruhto** [AnthorNet/SC-ProductionPlanner#77]
![image](https://github.com/user-attachments/assets/031db8c1-0bdd-4058-a384-d25b46c73989)
As you can see the site tells you need 3000x ionized fuel to output 250 MW.

**Comment by skupr** [comment]
It seems like it's changed, but not fixed
Current calculation for the same 250MW:
![image](https://github.com/user-attachments/assets/1aa8a4f7-3dc2-472a-8e5e-2a62303f73fa)
It just divided everything before to 1000.

There are actually two issues with it:
1. Inoized Fuel/Rocket fuel units are wrong (showing 3x instead of 3m<sup>2</sup>.
2. Numbers are currently wrong (1000 times less) for fuels measured in m<sup>2</sup>.

**Comment by AnthorNet** [comment]
Ooops sorry about it :D

Better now?

**Comment by skupr** [comment]
Thanks! Now it's fine!
